# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev", "test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change as needed

    - name: Create RDS instance
      run: |
        aws rds create-db-instance \
          --db-instance-identifier mydbinstance \
          --db-instance-class db.t3.micro \
          --engine postgres \
          --master-username saayam_ci \
          --master-user-password ${{ secrets.DB_PASSWORD }} \
          --allocated-storage 20 \
          --vpc-security-group-ids sg-0f8043500f5fecf35  # Use your security group
        aws rds wait db-instance-available --db-instance-identifier mydbinstance

    - name: Get RDS endpoint
      id: get-db-endpoint
      run: |
        DB_ENDPOINT=$(aws rds describe-db-instances --db-instance-identifier mydbinstance --query 'DBInstances[0].Endpoint.Address' --output text)
        echo "DB_ENDPOINT=${DB_ENDPOINT}" >> $GITHUB_ENV

    - name: Update application properties
      run: |
        echo "spring.datasource.url=jdbc:postgresql://${DB_ENDPOINT}:5432/mydatabase" > src/main/resources/application.properties
        echo "spring.datasource.username=admin" >> src/main/resources/application.properties
        echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> src/main/resources/application.properties
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Delete RDS instance
      if: always()  # Ensure RDS instance is deleted even if the build fails
      run: |
        aws rds delete-db-instance --db-instance-identifier mydbinstance --skip-final-snapshot
        aws rds wait db-instance-deleted --db-instance-identifier mydbinstance

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
